# Generated by Django 3.0.8 on 2020-07-25 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('expirationMonth', models.IntegerField()),
                ('expirationYear', models.IntegerField()),
                ('cvv', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammount', models.IntegerField()),
                ('currency', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('authorization_code', models.CharField(max_length=20)),
                ('time', models.DateTimeField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.cards')),
            ],
        ),
    ]
